name: PHPUnit

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Composer Cache
      uses: actions/cache@v4
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
